apiVersion: apps/v1
kind: Deployment
metadata:
  name: catgif
spec:
  replicas: 5
  selector:
    matchLabels:
      project: catgif
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        project: catgif
    spec: 
      containers:
      - name: example-ctr
        imagePullPolicy: Always
        image: nachikethmurthy/catgif:v1
        ports:
          - containerPort: 5000
      nodeSelector:
        favorite: wk-node

