apiVersion: v1
kind: Pod
metadata:
  name: hello-cat
  labels:
    zone: prod
    version: v1
spec:
  containers:
  - name: hello-ctr
    image: nachikethmurthy/catgif:v1
    ports:
    - containerPort: 5000
  nodeSelector:
    favorite: wk-node
