apiVersion: v1
kind: Service
metadata:
  name: svc-local
spec:
  type: LoadBalancer
  ports:
  - port: 6000 # Service IP Port
    protocol: TCP
    targetPort: 5000 # Container Port  
    nodePort: 31111 # Node Port
  selector:
    project: catgif
