apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: akatsuki
  name: default
---
apiVersion: v1
kind: Service
metadata:
  namespace: akatsuki
  name: cat-akatsuki
spec:
  type: NodePort
  ports:
  - nodePort: 31112
    port: 5000
    targetPort: 5000
  selector:
    env: manga
---
apiVersion: v1
kind: Pod
metadata:
  namespace: akatsuki
  name: madara
  labels:
    env: manga
spec:
  containers:
  - image: nachikethmurthy/catgif:v2
    name: cat-ctr
    ports:
    - containerPort: 5000
    imagePullPolicy: Always
