apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: leaf-village
  name: default
---
apiVersion: v1
kind: Service
metadata:
  namespace: leaf-village
  name: cat-naruto
spec:
  type: NodePort
  ports:
  - nodePort: 31111
    port: 5000
    targetPort: 5000
  selector:
    env: manga
---
apiVersion: v1
kind: Pod
metadata:
  namespace: leaf-village
  name: naruto
  labels:
    env: manga
spec:
  containers:
  - image: nachikethmurthy/catgif:v1
    name: cat-ctr
    ports:
    - containerPort: 5000
    imagePullPolicy: Always
